title: Guilherme Cruz
description: Espa√ßo desse desenvolvedor amante de Tartarugas Ninja e Pizza

url: http://gcruz.com.br
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Feed
   url: /feed.xml
 - title: Sobre
   url: /about

social:
  github: https://github.com/guicruzzs
  facebook: https://www.facebook.com/guilhermecruz.zs
  linkedin: https://www.linkedin.com/in/cruzguilherme
  twitter: https://twitter.com/cruzguilherm

google_analytics: "UA-54921110-2"
